#!/usr/bin/env python3
"""Translate AIOS Kit Chinese Markdown docs to English using an OpenAI-compatible API.

Secrets are read from environment variables. For legacy/private compatibility,
--secret-file may load an env file explicitly, but no project-specific env file
is read by default. The script never prints API key values.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import socket
import sys
import textwrap
import time
import urllib.error
import urllib.request
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SECRET_FILE: Path | None = None
DEFAULT_TARGET_LANG = "English"
DEFAULT_TARGET_CODE = "en"
DEFAULT_REQUEST_TIMEOUT_SECONDS = 300
DEFAULT_MAX_RETRIES = 3
SOURCE_FILES = [Path("README.md")]
SOURCE_GLOBS = ["docs/*.md", "docs/**/*.md"]
GENERATED_MARKER = "<!-- AUTO-GENERATED FILE. DO NOT EDIT. -->"
GENERATED_NOTICE = "This file is automatically generated from the Chinese source. Please edit the Chinese source file instead."
TRANSLATION_METADATA_LABEL = "AIOS-TRANSLATION-METADATA"
TRANSLATION_METADATA_SCHEMA = "aios.translation.v1"
TRANSLATION_STATUS_GENERATED = "generated"
TRANSLATION_STATUS_STALE_LEGACY = "stale-legacy"
SHA256_PATTERN = re.compile(r"^[0-9a-f]{64}$")
CHUNK_SPLITTER_VERSION = "markdown-heading-paragraph-v1"

SYSTEM_PROMPT = """You are a careful technical documentation translator.
Translate Simplified Chinese Markdown documentation into natural, concise English.
Preserve Markdown structure, frontmatter keys, code fences, inline code, links, HTML comments, tables, and command examples.
Do not add new sections. Do not remove content. Translate prose only.
Keep product names and file paths unchanged unless they are natural language labels.
""".strip()


def load_env_file(path: Path) -> None:
    if not path.exists():
        return
    for raw in path.read_text(encoding="utf-8", errors="replace").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip()
        if (value.startswith("'") and value.endswith("'")) or (value.startswith('"') and value.endswith('"')):
            value = value[1:-1]
        value = value.replace("'\\''", "'")
        os.environ.setdefault(key, value)


def require_env(name: str) -> str:
    value = os.environ.get(name, "")
    if not value:
        raise SystemExit(f"Missing required environment variable: {name}")
    return value


def env_int(name: str, default: int, minimum: int = 1) -> int:
    raw = os.environ.get(name, "").strip()
    if not raw:
        return default
    try:
        value = int(raw)
    except ValueError as exc:
        raise SystemExit(f"{name} must be an integer, got: {raw!r}") from exc
    if value < minimum:
        raise SystemExit(f"{name} must be >= {minimum}, got: {value}")
    return value


def api_config() -> dict[str, str | int]:
    return {
        "base_url": require_env("TRANSLATE_BASE_URL").rstrip("/"),
        "api_key": require_env("TRANSLATE_API_KEY"),
        "model": require_env("TRANSLATE_MODEL"),
        "api_mode": os.environ.get("TRANSLATE_API_MODE", "chat_completions").strip().lower() or "chat_completions",
        "timeout_seconds": env_int("TRANSLATE_TIMEOUT_SECONDS", DEFAULT_REQUEST_TIMEOUT_SECONDS),
        "max_retries": env_int("TRANSLATE_MAX_RETRIES", DEFAULT_MAX_RETRIES),
    }


def request_json(url: str, api_key: str, payload: dict[str, Any], timeout: int, max_retries: int) -> dict[str, Any]:
    body = json.dumps(payload, ensure_ascii=False).encode("utf-8")
    req = urllib.request.Request(
        url,
        data=body,
        method="POST",
        headers={
            "Authorization": f"Bearer {api_key}",
            "User-Agent": "OpenAI/Python 2.24.0",
            "Content-Type": "application/json",
            "Accept": "application/json",
        },
    )
    for attempt in range(1, max_retries + 1):
        try:
            with urllib.request.urlopen(req, timeout=timeout) as resp:
                text = resp.read().decode("utf-8", errors="replace")
                return json.loads(text)
        except urllib.error.HTTPError as exc:
            detail = exc.read().decode("utf-8", errors="replace")[:1000]
            if exc.code < 500 or attempt == max_retries:
                raise RuntimeError(f"API HTTP {exc.code} from {url}: {detail}") from exc
            print(
                f"API HTTP {exc.code}; retrying request {attempt + 1}/{max_retries} after backoff...",
                file=sys.stderr,
            )
        except (TimeoutError, socket.timeout, urllib.error.URLError) as exc:
            if attempt == max_retries:
                raise RuntimeError(
                    f"API request failed after {max_retries} attempts "
                    f"(timeout={timeout}s): {exc}"
                ) from exc
            print(
                f"API request failed ({type(exc).__name__}: {exc}); "
                f"retrying request {attempt + 1}/{max_retries} after backoff...",
                file=sys.stderr,
            )
        time.sleep(min(2 ** (attempt - 1), 10))
    raise RuntimeError("unreachable: API request retry loop exhausted")


def extract_response_text(data: dict[str, Any]) -> str:
    if isinstance(data.get("output_text"), str):
        return data["output_text"].strip()
    output = data.get("output")
    if isinstance(output, list):
        parts: list[str] = []
        for item in output:
            if not isinstance(item, dict):
                continue
            content = item.get("content")
            if isinstance(content, list):
                for c in content:
                    if isinstance(c, dict):
                        text = c.get("text") or c.get("content")
                        if isinstance(text, str):
                            parts.append(text)
            elif isinstance(content, str):
                parts.append(content)
        if parts:
            return "\n".join(parts).strip()
    choices = data.get("choices")
    if isinstance(choices, list) and choices:
        msg = choices[0].get("message", {}) if isinstance(choices[0], dict) else {}
        content = msg.get("content")
        if isinstance(content, str):
            return content.strip()
    raise RuntimeError(f"Could not extract text from API response keys: {sorted(data.keys())}")


def call_model(prompt: str, user_text: str, cfg: dict[str, str | int]) -> str:
    mode = str(cfg["api_mode"])
    if mode in {"responses", "codex_responses", "openai_responses"}:
        url = str(cfg["base_url"]) + "/responses"
        payload = {
            "model": cfg["model"],
            "input": [
                {"role": "system", "content": prompt},
                {"role": "user", "content": user_text},
            ],
        }
    else:
        url = str(cfg["base_url"]) + "/chat/completions"
        payload = {
            "model": cfg["model"],
            "messages": [
                {"role": "system", "content": prompt},
                {"role": "user", "content": user_text},
            ],
            "temperature": 0.2,
        }
    return extract_response_text(
        request_json(
            url,
            str(cfg["api_key"]),
            payload,
            int(cfg["timeout_seconds"]),
            int(cfg["max_retries"]),
        )
    )


def source_files() -> list[Path]:
    files = [ROOT / p for p in SOURCE_FILES if (ROOT / p).exists()]
    for pattern in SOURCE_GLOBS:
        files.extend(sorted(ROOT.glob(pattern)))

    seen: set[Path] = set()
    sources: list[Path] = []
    for path in files:
        rel = path.relative_to(ROOT)
        if not path.is_file() or any(part in {"en", "translations"} for part in rel.parts):
            continue
        if rel in seen:
            continue
        seen.add(rel)
        sources.append(path)
    return sources


def resolve_only_sources(values: list[str]) -> list[Path]:
    allowed = {p.relative_to(ROOT) for p in source_files()}
    resolved: list[Path] = []
    errors: list[str] = []
    for raw in values:
        rel = Path(raw)
        if rel.is_absolute() or ".." in rel.parts:
            errors.append(f"unsafe path: {raw}")
            continue
        if rel not in allowed:
            errors.append(f"not a translatable source doc: {raw}")
            continue
        resolved.append(ROOT / rel)
    if errors:
        raise SystemExit("Invalid --only values:\n- " + "\n- ".join(errors))
    # Keep deterministic source order and drop duplicates.
    requested = set(resolved)
    return [p for p in source_files() if p in requested]


def target_path(source: Path, target_code: str) -> Path:
    rel = source.relative_to(ROOT)
    if rel == Path("README.md"):
        return ROOT / "translations" / target_code / "README.md"
    return ROOT / "translations" / target_code / rel


def chinese_link_for(target: Path, target_code: str) -> str:
    rel = target.relative_to(ROOT)
    if rel == Path("translations") / target_code / "README.md":
        return "../../README.md"
    if len(rel.parts) >= 2 and rel.parts[:2] == ("translations", target_code):
        source_rel = Path(*rel.parts[2:])
        return os.path.relpath(ROOT / source_rel, target.parent).replace(os.sep, "/")
    return "../../README.md"


def source_sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def translation_metadata_comment(
    source: Path,
    *,
    status: str = TRANSLATION_STATUS_GENERATED,
    generated_source_sha256: str | None = None,
    historical_source_sha256: str | None = None,
) -> str:
    if status not in {TRANSLATION_STATUS_GENERATED, TRANSLATION_STATUS_STALE_LEGACY}:
        raise ValueError(f"unsupported translation status: {status}")
    metadata: dict[str, str] = {
        "schema": TRANSLATION_METADATA_SCHEMA,
        "source_path": source.relative_to(ROOT).as_posix(),
    }
    if status == TRANSLATION_STATUS_GENERATED:
        source_hash = generated_source_sha256 or source_sha256(source)
        if not SHA256_PATTERN.fullmatch(source_hash):
            raise ValueError("generated source SHA must be a lowercase SHA-256 hex digest")
        metadata["source_sha256"] = source_hash
    elif historical_source_sha256 is not None:
        if not SHA256_PATTERN.fullmatch(historical_source_sha256):
            raise ValueError("historical source SHA must be a lowercase SHA-256 hex digest")
        metadata["source_sha256"] = historical_source_sha256
    metadata["status"] = status
    encoded = json.dumps(metadata, ensure_ascii=False, separators=(",", ":"))
    return f"<!-- {TRANSLATION_METADATA_LABEL} {encoded} -->"


def generated_header(
    source: Path,
    target: Path,
    target_code: str,
    target_lang: str,
    *,
    status: str = TRANSLATION_STATUS_GENERATED,
    generated_source_sha256: str | None = None,
    historical_source_sha256: str | None = None,
) -> str:
    zh = chinese_link_for(target, target_code)
    metadata = translation_metadata_comment(
        source,
        status=status,
        generated_source_sha256=generated_source_sha256,
        historical_source_sha256=historical_source_sha256,
    )
    return f"{GENERATED_MARKER}\n{metadata}\n\n[简体中文]({zh}) | **{target_lang}**\n\n> {GENERATED_NOTICE}\n\n"


def strip_source_language_switch(text: str) -> str:
    # README.md has a source-side language switch. Generated files get their
    # own header, so translating the source switch would create duplicate links.
    return re.sub(r"\n?\*\*简体中文\*\*\s*\|\s*\[English\]\([^)]*\)\n+", "\n", text, count=1)


def strip_translated_language_switch(text: str) -> str:
    return re.sub(r"\n?\*\*(?:Simplified Chinese|Chinese|简体中文)\*\*\s*\|\s*\[English\]\([^)]*\)\n+", "\n", text, count=1, flags=re.I)


def rewrite_markdown_links(translated: str, source: Path, target: Path, target_code: str) -> str:
    """Rewrite repository-internal Markdown links for the generated file location.

    Each generated file header already links back to the Simplified Chinese source.
    Body links between translatable docs point to generated counterparts. Links to
    existing Markdown files without generated counterparts point back to their
    canonical source paths instead of retaining a now-broken relative path.
    """
    known_sources = {p.resolve(): target_path(p, target_code) for p in source_files()}
    root = ROOT.resolve()

    def repl(match: re.Match[str]) -> str:
        label, url = match.group(1), match.group(2)
        if re.match(r"^[a-z][a-z0-9+.-]*:", url, re.I) or url.startswith(("#", "/")):
            return match.group(0)
        path_part, sep, fragment = url.partition("#")
        if not path_part.endswith(".md"):
            return match.group(0)
        source_target = (source.parent / path_part).resolve()
        try:
            source_target.relative_to(root)
        except ValueError:
            return match.group(0)
        generated = known_sources.get(source_target)
        link_target = generated or (source_target if source_target.is_file() else None)
        if not link_target:
            return match.group(0)
        rel = os.path.relpath(link_target, target.parent).replace(os.sep, "/")
        if sep:
            rel = rel + "#" + fragment
        return f"[{label}]({rel})"

    return re.sub(r"(?<!!)\[([^\]]+)\]\(([^)\s]+)\)", repl, translated)


def strip_existing_generated_header(text: str) -> str:
    if not text.startswith(GENERATED_MARKER):
        return text
    # Remove the generated marker, optional metadata, and notice when a model
    # echoes an existing generated file.
    try:
        return generated_body_bytes(text.encode("utf-8")).decode("utf-8")
    except (UnicodeDecodeError, ValueError):
        return text


def sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def generated_body_bytes(content: bytes) -> bytes:
    marker = re.escape(GENERATED_MARKER.encode("utf-8"))
    metadata = re.escape(f"<!-- {TRANSLATION_METADATA_LABEL} ".encode("utf-8")) + rb"[^\n]* -->\n"
    notice = re.escape(("> " + GENERATED_NOTICE + "\n\n").encode("utf-8"))
    language_switch = re.escape("[简体中文]".encode("utf-8")) + rb"\([^\n)]*\) \| \*\*[^\n*]+\*\*\n\n"
    header = re.compile(
        rb"\A"
        + marker
        + rb"\n(?:"
        + metadata
        + rb")?\n"
        + language_switch
        + notice
    )
    match = header.match(content)
    if match is None:
        raise ValueError("generated header is missing or incomplete")
    return content[match.end() :]


def parse_translation_metadata(content: bytes) -> dict[str, str]:
    try:
        text = content.decode("utf-8")
    except UnicodeDecodeError as exc:
        raise ValueError("target is not valid UTF-8") from exc
    lines = text.splitlines()
    if not lines or lines[0] != GENERATED_MARKER:
        raise ValueError("generated marker is missing")
    prefix = f"<!-- {TRANSLATION_METADATA_LABEL} "
    suffix = " -->"
    if len(lines) < 2 or not lines[1].startswith(prefix) or not lines[1].endswith(suffix):
        raise ValueError("translation metadata comment is missing")
    raw_json = lines[1][len(prefix) : -len(suffix)]
    try:
        metadata = json.loads(raw_json)
    except json.JSONDecodeError as exc:
        raise ValueError("translation metadata is not valid JSON") from exc
    if not isinstance(metadata, dict) or any(not isinstance(k, str) or not isinstance(v, str) for k, v in metadata.items()):
        raise ValueError("translation metadata must be a string map")
    if metadata.get("schema") != TRANSLATION_METADATA_SCHEMA:
        raise ValueError("translation metadata schema is unsupported")
    if not metadata.get("source_path"):
        raise ValueError("translation metadata source_path is missing")
    status = metadata.get("status")
    if status not in {TRANSLATION_STATUS_GENERATED, TRANSLATION_STATUS_STALE_LEGACY}:
        raise ValueError("translation metadata status is unsupported")
    source_hash = metadata.get("source_sha256")
    if status == TRANSLATION_STATUS_GENERATED and (source_hash is None or not SHA256_PATTERN.fullmatch(source_hash)):
        raise ValueError("generated metadata requires a valid source_sha256")
    if source_hash is not None and not SHA256_PATTERN.fullmatch(source_hash):
        raise ValueError("source_sha256 is not a valid SHA-256 digest")
    try:
        generated_body_bytes(content)
    except ValueError as exc:
        raise ValueError(f"generated header is incomplete: {exc}") from exc
    return metadata


def check_translation_target(source: Path, target: Path) -> tuple[bool, str]:
    source_display = display_path(source)
    target_display = display_path(target)
    if not source.is_file():
        return False, f"missing source: {source_display}"
    if not target.is_file():
        return False, f"missing target: {target_display}"
    try:
        metadata = parse_translation_metadata(target.read_bytes())
    except (OSError, ValueError) as exc:
        return False, f"malformed target {target_display}: {exc}"
    expected_source = source.relative_to(ROOT).as_posix()
    if metadata.get("source_path") != expected_source:
        return False, (
            f"malformed target {target_display}: source_path={metadata.get('source_path')!r}; "
            f"expected {expected_source!r}"
        )
    status = metadata["status"]
    if status == TRANSLATION_STATUS_STALE_LEGACY:
        return False, f"stale-legacy target: {target_display}"
    actual_hash = source_sha256(source)
    recorded_hash = metadata["source_sha256"]
    if recorded_hash != actual_hash:
        return False, (
            f"stale target {target_display}: source_sha256={recorded_hash}; "
            f"current={actual_hash}"
        )
    return True, f"fresh target: {target_display} (source={source_display}, sha256={actual_hash})"


def resolve_check_targets(values: list[str], target_code: str, *, check_all: bool = False) -> list[tuple[Path, Path]]:
    pairs = [(source, target_path(source, target_code)) for source in source_files()]
    if check_all:
        return pairs
    by_target = {target.relative_to(ROOT).as_posix(): (source, target) for source, target in pairs}
    resolved: list[tuple[Path, Path]] = []
    errors: list[str] = []
    for raw in values:
        rel = Path(raw)
        if rel.is_absolute() or ".." in rel.parts:
            errors.append(f"invalid --check target: unsafe path: {raw}")
            continue
        key = rel.as_posix()
        pair = by_target.get(key)
        if pair is None:
            errors.append(f"invalid --check target: not a generated target: {raw}")
            continue
        if pair not in resolved:
            resolved.append(pair)
    if errors:
        raise ValueError("\n".join(errors))
    return resolved


def run_freshness_checks(pairs: list[tuple[Path, Path]]) -> int:
    failed = False
    for source, target in pairs:
        fresh, detail = check_translation_target(source, target)
        print(("PASS " if fresh else "FAIL ") + detail, file=sys.stdout if fresh else sys.stderr)
        failed = failed or not fresh
    return 1 if failed else 0


def mark_stale_legacy(
    source: Path,
    target: Path,
    target_code: str,
    target_lang: str,
    *,
    historical_source_sha256: str | None = None,
) -> bool:
    """Rewrite only the owner-generated header, retaining the body byte-for-byte."""
    original = target.read_bytes()
    body = generated_body_bytes(original)
    header = generated_header(
        source,
        target,
        target_code,
        target_lang,
        status=TRANSLATION_STATUS_STALE_LEGACY,
        historical_source_sha256=historical_source_sha256,
    ).encode("utf-8")
    updated = header + body
    if updated == original:
        return False
    target.write_bytes(updated)
    return True


def split_large_section(section: str, max_chars: int) -> list[str]:
    """Split a too-large Markdown section on blank-line paragraph boundaries."""
    if max_chars <= 0 or len(section) <= max_chars:
        return [section]
    parts = re.split(r"(\n\s*\n)", section)
    paragraphs: list[str] = []
    for i in range(0, len(parts), 2):
        para = parts[i]
        sep = parts[i + 1] if i + 1 < len(parts) else ""
        if para or sep:
            paragraphs.append(para + sep)
    chunks: list[str] = []
    current = ""
    for para in paragraphs:
        if current and len(current) + len(para) > max_chars:
            chunks.append(current.rstrip() + "\n")
            current = para
        else:
            current += para
    if current.strip():
        chunks.append(current.rstrip() + "\n")
    return chunks or [section]


def split_markdown_chunks(text: str, max_chars: int) -> list[str]:
    """Split Markdown into recoverable chunks, preferring headings outside fences."""
    if max_chars <= 0 or len(text) <= max_chars:
        return [text]
    sections: list[str] = []
    current: list[str] = []
    in_fence = False
    for line in text.splitlines(keepends=True):
        if line.lstrip().startswith("```") or line.lstrip().startswith("~~~"):
            in_fence = not in_fence
        if not in_fence and re.match(r"^#{1,3}\s+", line) and current:
            sections.append("".join(current))
            current = [line]
        else:
            current.append(line)
    if current:
        sections.append("".join(current))

    expanded: list[str] = []
    for section in sections:
        expanded.extend(split_large_section(section, max_chars))

    chunks: list[str] = []
    current_text = ""
    for section in expanded:
        if current_text and len(current_text) + len(section) > max_chars:
            chunks.append(current_text.rstrip() + "\n")
            current_text = section
        else:
            current_text += section
    if current_text.strip():
        chunks.append(current_text.rstrip() + "\n")
    return chunks or [text]


def cache_path_for(source: Path, target_code: str, checkpoint_dir: Path) -> Path:
    root = checkpoint_dir if checkpoint_dir.is_absolute() else ROOT / checkpoint_dir
    rel = source.relative_to(ROOT)
    return root / target_code / rel.with_suffix(rel.suffix + ".json")


def display_path(path: Path) -> str:
    try:
        return str(path.relative_to(ROOT))
    except ValueError:
        return str(path)


def load_translation_cache(path: Path, source_hash: str, chunks: list[str]) -> dict[int, str]:
    if not path.exists():
        return {}
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return {}
    if data.get("source_sha256") != source_hash:
        return {}
    if data.get("chunk_splitter") not in (None, CHUNK_SPLITTER_VERSION):
        return {}
    if data.get("chunk_count") not in (None, len(chunks)):
        return {}
    cached_chunks = data.get("chunks")
    if not isinstance(cached_chunks, list):
        return {}
    out: dict[int, str] = {}
    for item in cached_chunks:
        if not isinstance(item, dict):
            continue
        index = item.get("index")
        translation = item.get("translation")
        chunk_hash = item.get("source_sha256")
        if not isinstance(index, int) or not isinstance(translation, str):
            continue
        if index < 0 or index >= len(chunks):
            continue
        if chunk_hash != sha256_text(chunks[index]):
            continue
        out[index] = translation
    return out


def save_translation_cache(path: Path, source: Path, source_hash: str, chunks: list[str], translations: dict[int, str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "schema": "aios-kit.translate-cache.v1",
        "source": source.relative_to(ROOT).as_posix(),
        "source_sha256": source_hash,
        "chunk_splitter": CHUNK_SPLITTER_VERSION,
        "chunk_count": len(chunks),
        "updated_at": time.strftime("%Y-%m-%dT%H:%M:%S%z"),
        "chunks": [
            {"index": i, "source_sha256": sha256_text(chunks[i]), "translation": translations[i]}
            for i in sorted(translations)
        ],
    }
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def translate_chunked_file(source: Path, original: str, cfg: dict[str, str | int], target_code: str, target_lang: str, *, max_chars: int, resume: bool, checkpoint_dir: Path) -> tuple[Path, str]:
    rel = source.relative_to(ROOT).as_posix()
    target = target_path(source, target_code)
    chunks = split_markdown_chunks(original, max_chars)
    source_hash = sha256_text(original)
    cache_path = cache_path_for(source, target_code, checkpoint_dir)
    translations = load_translation_cache(cache_path, source_hash, chunks) if resume else {}
    if translations:
        print(f"  resume cache: {display_path(cache_path)} ({len(translations)}/{len(chunks)} chunks)")
    for idx, chunk in enumerate(chunks):
        if idx in translations:
            print(f"  chunk {idx + 1}/{len(chunks)} cached")
            continue
        prompt = SYSTEM_PROMPT + "\n\nYou are translating one recoverable chunk from a larger Markdown file. Return only translated Markdown for this chunk."
        user = f"Translate this Markdown chunk to {target_lang}. File path: {rel}. Chunk: {idx + 1}/{len(chunks)}.\n\n{chunk}"
        print(f"  translating chunk {idx + 1}/{len(chunks)} ({len(chunk)} chars)")
        translations[idx] = call_model(prompt, user, cfg)
        save_translation_cache(cache_path, source, source_hash, chunks, translations)
    translated = "\n\n".join(translations[i].strip() for i in range(len(chunks))).strip() + "\n"
    return target, translated


def translate_file(source: Path, cfg: dict[str, str | int], target_code: str, target_lang: str, *, chunk_max_chars: int = 0, resume: bool = False, checkpoint_dir: Path = Path(".cache/translate-docs")) -> tuple[Path, str]:
    source_bytes = source.read_bytes()
    original = strip_source_language_switch(source_bytes.decode("utf-8"))
    if chunk_max_chars > 0:
        target, translated = translate_chunked_file(
            source,
            original,
            cfg,
            target_code,
            target_lang,
            max_chars=chunk_max_chars,
            resume=resume,
            checkpoint_dir=checkpoint_dir,
        )
    else:
        rel = source.relative_to(ROOT).as_posix()
        user = f"Translate this Markdown file to {target_lang}. File path: {rel}\n\n{original}"
        translated = call_model(SYSTEM_PROMPT, user, cfg)
        target = target_path(source, target_code)
    translated = strip_existing_generated_header(translated).strip() + "\n"
    translated = strip_translated_language_switch(translated).strip() + "\n"
    translated = rewrite_markdown_links(translated, source, target, target_code).strip() + "\n"
    return target, generated_header(
        source,
        target,
        target_code,
        target_lang,
        generated_source_sha256=hashlib.sha256(source_bytes).hexdigest(),
    ) + translated


def write_if_changed(path: Path, content: str) -> bool:
    old = path.read_text(encoding="utf-8") if path.exists() else None
    if old == content:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


def check_api(cfg: dict[str, str | int]) -> None:
    text = call_model(
        "You are a health-check endpoint for a documentation translation workflow. Reply with exactly: ok",
        "Reply with exactly: ok",
        cfg,
    )
    normalized = re.sub(r"[^a-z]", "", text.lower())
    if "ok" not in normalized:
        raise RuntimeError(f"Unexpected API health-check response shape: {text[:80]!r}")
    host_hint = re.sub(r"//([^/@:]+)(:[0-9]+)?", r"//<host>\2", str(cfg["base_url"]))
    print("API check passed")
    print(f"- base_url_host_hint: {host_hint}")
    print(f"- model: {cfg['model']}")
    print(f"- api_mode: {cfg['api_mode']}")
    print(f"- timeout_seconds: {cfg['timeout_seconds']}")
    print(f"- max_retries: {cfg['max_retries']}")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--secret-file", type=Path, default=DEFAULT_SECRET_FILE, help="optional legacy/private env file to load before reading TRANSLATE_* from the environment")
    parser.add_argument("--target-code", default=DEFAULT_TARGET_CODE)
    parser.add_argument("--target-language", default=DEFAULT_TARGET_LANG)
    parser.add_argument("--check-api", action="store_true")
    freshness = parser.add_mutually_exclusive_group()
    freshness.add_argument("--check", action="append", default=[], metavar="TARGET", help="offline source-freshness check for one generated target; may be repeated")
    freshness.add_argument("--check-all", action="store_true", help="offline source-freshness diagnostic for every generated target")
    parser.add_argument("--write", action="store_true", help="write translated files")
    parser.add_argument("--dry-run", action="store_true", help="show planned files without calling translation for all files")
    parser.add_argument("--limit", type=int, default=0, help="limit number of files translated; useful for smoke tests")
    parser.add_argument("--only", action="append", default=[], help="relative source path to translate; may be repeated")
    parser.add_argument("--chunk-max-chars", type=int, default=0, help="split each Markdown file into recoverable chunks up to roughly this many characters; 0 keeps the legacy whole-file request")
    parser.add_argument("--resume", action="store_true", help="reuse completed chunk translations from --checkpoint-dir when --chunk-max-chars is set")
    parser.add_argument("--checkpoint-dir", type=Path, default=Path(".cache/translate-docs"), help="local ignored directory for chunk translation checkpoints")
    args = parser.parse_args()

    if args.check or args.check_all:
        incompatible = (
            args.secret_file
            or args.check_api
            or args.write
            or args.dry_run
            or args.limit
            or args.only
            or args.chunk_max_chars
            or args.resume
            or args.checkpoint_dir != Path(".cache/translate-docs")
        )
        if incompatible:
            print("Freshness checks cannot be combined with translation/API options.", file=sys.stderr)
            return 2
        try:
            pairs = resolve_check_targets(args.check, args.target_code, check_all=args.check_all)
        except ValueError as exc:
            print(str(exc), file=sys.stderr)
            return 2
        return run_freshness_checks(pairs)

    if args.secret_file:
        load_env_file(args.secret_file)

    files = source_files()
    if args.only:
        files = resolve_only_sources(args.only)
    if args.limit:
        files = files[: args.limit]

    planned = [(p, target_path(p, args.target_code)) for p in files]
    print(f"Translation source files: {len(planned)}")
    for src, dst in planned:
        print(f"- {src.relative_to(ROOT)} -> {dst.relative_to(ROOT)}")
        if args.chunk_max_chars > 0:
            original = strip_source_language_switch(src.read_text(encoding="utf-8"))
            chunk_count = len(split_markdown_chunks(original, args.chunk_max_chars))
            cache_path = cache_path_for(src, args.target_code, args.checkpoint_dir)
            print(f"  chunks: {chunk_count}; checkpoint: {display_path(cache_path)}")

    if args.dry_run and not args.write:
        if args.check_api:
            cfg = api_config()
            check_api(cfg)
        return 0
    cfg = api_config()
    if args.check_api:
        check_api(cfg)
    if not args.write:
        print("No files written. Pass --write to generate translations.")
        return 0

    changed = 0
    started = time.time()
    for idx, src in enumerate(files, 1):
        print(f"Translating {idx}/{len(files)}: {src.relative_to(ROOT)}")
        dst, content = translate_file(src, cfg, args.target_code, args.target_language, chunk_max_chars=args.chunk_max_chars, resume=args.resume, checkpoint_dir=args.checkpoint_dir)
        if write_if_changed(dst, content):
            changed += 1
            print(f"  wrote {dst.relative_to(ROOT)}")
        else:
            print(f"  unchanged {dst.relative_to(ROOT)}")
    print(f"Translation complete: changed_files={changed}, elapsed_seconds={time.time() - started:.1f}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
